on: [push]

name: commit

jobs:
  check:
    name: check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: 'docker compose up --build --exit-code-from app'
      - run: 'git status --porcelain'
      - uses: actions/upload-artifact@v4
        with:
          name: pkg
          path: ./src/wasm/pkg/
      - run: '[[ -z $(git status --porcelain) ]]'
