on:
  push:
    tags:
    - "*"

name: release

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: "docker compose up --build --exit-code-from app"
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./src/wasm/pkg/
      - run: "git status --porcelain"
      - run: "! !! | (grep -q .)"
      - run: "npm diff --diff=@hazae41/memory.wasm@${{github.ref_name}} --diff=."
      - run: "! !! | (grep -q .)"