on:
  push:
    tags:
    - "*"

name: release

jobs:
  wasm:
    name: wasm
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: "docker compose up --build --exit-code-from app"
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./src/wasm/pkg/
      - run: "! (git status --porcelain) | (tee /dev/tty) | (grep -q .)"
      - run: "npm ci"
      - run: "! (npm diff --diff=@hazae41/memory.wasm@${{github.ref_name}} --diff=.) | (tee /dev/tty) | (grep -q .)"